# deepseek-model-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-model-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""