apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen2.5-72b-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""